import Inputs from '\\..\\resources\\inputs.json';

const email = Inputs.user.email;
const password = Inputs.user.pass;
const account1 = Inputs.accounts.accountBasic;
const account2 = Inputs.accounts.accountFlex;
const movement1 = Inputs.movements.movementDesPend

describe('Account - Behaviour Operations', () => {
    before(() => {
        cy.visit('https://seubarriga.wcaquino.me/login')
        cy.get('input[id="email"]')
            .type(email)
        cy.get('input[id="senha"]')
            .type(password)
        cy.get('button[type="submit"]')
            .click()
        cy.contains('a[data-toggle="dropdown"]', 'Contas')
            .click()
        cy.contains('a[href="/addConta"]', 'Adicionar')
            .click()
        cy.get('input[id="nome"]')
            .type(account1)
        cy.get('button[type="submit"]')
            .click()
        cy.contains('a[data-toggle="dropdown"]', 'Contas')
            .click()
        cy.contains('a[href="/addConta"]', 'Adicionar')
            .click()
        cy.get('input[id="nome"]')
            .type(account2)
        cy.get('button[type="submit"]')
            .click()
        cy.contains('a[href="/movimentacao"]', 'Criar Movimentação')
            .click()
        cy.get('select[id="tipo"]')
            .select(movement1.movementType)
        cy.get('input[id="data_transacao"]')
            .type(movement1.movementDate)
        cy.get('input[id="data_pagamento"]')
            .type(movement1.payDay)
        cy.get('input[id="descricao"]')
            .type(movement1.description)
        cy.get('input[id="interessado"]')
            .type(movement1.interested)
        cy.get('input[id="valor"]')
            .type(movement1.value)
        cy.get('select[id="conta"]')
            .select(account2)
        cy.get(`input[id="status_${movement1.status}"]`)
            .click()
        cy.get('button[type="submit"]')
            .click()
        cy.contains('a[href="/movimentacao"]', 'Criar Movimentação')
            .click()
        cy.get('select[id="tipo"]')
            .select(movement1.movementType)
        cy.get('input[id="data_transacao"]')
            .type(movement1.movementDate)
        cy.get('input[id="data_pagamento"]')
            .type(movement1.payDay)
        cy.get('input[id="descricao"]')
            .type(movement1.description)
        cy.get('input[id="interessado"]')
            .type(movement1.interested)
        cy.get('input[id="valor"]')
            .type(movement1.value)
        cy.get('select[id="conta"]')
            .select(account1)
        cy.get(`input[id="status_${movement1.status}"]`)
            .click()
        cy.get('button[type="submit"]')
            .click()
    })

    beforeEach(() => {
        cy.visit('https://seubarriga.wcaquino.me/login')
        cy.get('input[id="email"]')
            .type(email)
        cy.get('input[id="senha"]')
            .type(password)
        cy.get('button[type="submit"]')
            .click()
    })

    it('Tries to delete an account with active movements', () => {
        cy.contains('a[data-toggle="dropdown"]', 'Contas')
            .click()
        cy.contains('a[href="/contas"]', 'Listar')
            .click()
        cy.get('td')
            .first()
            .next()
            .children()
            .last()
            .click()
        cy.get('div[class="alert alert-danger"]')
            .should('have.text', 'Conta em uso na movimentações')
    })

    it('Tries to rename an account to an existing account name', () => {
        cy.contains('a[data-toggle="dropdown"]', 'Contas')
            .click()
        cy.contains('a[href="/contas"]', 'Listar')
            .click()
        cy.get('td')
            .first()
            .next()
            .children()
            .first()
            .click()
        cy.get('input[id="nome"]')
            .clear()
            .type(account2)
        cy.get('button[type="submit"]')
            .click()
        cy.get('div[class="alert alert-danger"]')
            .should('have.text', 'Já existe uma conta com esse nome!')
    })

    it('Tries to create an account with a name from an active account', () => {
        cy.contains('a[data-toggle="dropdown"]', 'Contas')
            .click()
        cy.contains('a[href="/addConta"]', 'Adicionar')
            .click()
        cy.get('input[id="nome"]')
            .type(account1)
        cy.get('button[type="submit"]')
            .click()
        cy.get('div[class="alert alert-danger"]')
            .should('have.text', 'Já existe uma conta com esse nome!')
    })

    after(() => {
        cy.contains('a[href="/extrato"]', 'Resumo Mensal')
            .click()
        cy.get('select[id="mes"]')
            .select("10")
        cy.get('select[id="ano"]')
            .select("2021")
        cy.get('input[type="submit"]')
            .click()
        cy.get('span[class="glyphicon glyphicon-remove-circle"]')
            .first()
            .click()
        cy.get('span[class="glyphicon glyphicon-remove-circle"]')
            .first()
            .click()
        cy.contains('a[data-toggle="dropdown"]', 'Contas')
            .click()
        cy.contains('a[href="/contas"]', 'Listar')
            .click()
            cy.get('span[class="glyphicon glyphicon-remove-circle"]')
            .first()
            .click()
        cy.get('span[class="glyphicon glyphicon-remove-circle"]')
            .first()
            .click()
    })
})